[Feat] 날짜 변경되는 시점에 <오늘> 날짜 업데이트 hook
f-lab-edu/taptap pull request #8
Opened 2023-10-31 09:00 UTC by yesl-kim

@f-lab-jake 

close #7

2023-10-31 15:02 UTC, f-lab-jake requested changes

2023-10-31 15:02 UTC, f-lab-jake commented on web/src/hooks/useToday.tsx
> +    )
지금 최대 1분 늦게 날짜 변경이 반영될수 있겠죠? 딱맞춰서 하려면 어떻게해야할까요?

2023-11-01 00:53 UTC, yesl-kim commented on web/src/hooks/useToday.tsx
> +    )
그럼 시간 간격을 1초로 줄이면 될 것 같아요  ˙Ⱉ˙ 

2023-11-01 09:49 UTC, f-lab-jake commented on web/src/hooks/useToday.tsx
> +    )
저런  지속적으로 확인하는 방식을 polling이라고 하는데요, polling을 하지 말아봅시다.

2023-11-02 14:59 UTC, f-lab-jake requested changes

2023-11-02 14:59 UTC, f-lab-jake commented on web/src/hooks/useToday.tsx
> +    schedule.scheduleJob('0 0 0 * * *', (date) => setToday(date))
이게 사실 https://www.npmjs.com/package/react-timer-hook 요런 훅이 있어서 그냥 쓰면 됩니다.
근데 굳이 만들어보라한건 직접 타이밍을 다루는 로직을 짜보라한건데 요런 라이브러리를 쓴건 의도에 어긋납니다. 아예 hook을 쓰면 되거든요.

2023-11-03 06:28 UTC, yesl-kim commented on web/src/hooks/useToday.tsx
> +    schedule.scheduleJob('0 0 0 * * *', (date) => setToday(date))
아하 그렇군요 👀
다시 수정해봤습니다! 
35a979b19b54c3368dcb2046e73a85349e026578

2023-11-03 06:55 UTC, f-lab-jake requested changes

2023-11-03 06:55 UTC, f-lab-jake commented on web/src/hooks/useToday.tsx
> +    setTimeout(() => setToday(new Date()), delay)
`getTime(startOfDay(addDays(today, 1)))` 요 값과
`setToday(new Date())`의 값이 정확히 일치할거라는 가정이 숨겨져 있습니다. 아마 해도되는 옳은 가정이긴 할겁니다.
그런데 `setTimeout`을 약간 덜 신뢰한다면(가령 1ms정도는 먼저 불리거나 뒤에 불릴수있어서 저 두값이 일치하지 않을경우) 어떻게 해야할까요?

그리고 cleanup 동작이 필요합니다. 메모리 누수가 있습니다.

2023-11-06 11:31 UTC, f-lab-jake requested changes

2023-11-06 11:31 UTC, f-lab-jake commented on web/src/hooks/useToday.tsx
> +    const id = setTimeout(() => setToday(new Date()), delay)
요지는 여기서 `new Date()`대신에 `next`를 써야한단겁니다. `next`보단 `tomorrow`가 낫겠네요.

2023-11-07 06:37 UTC, yesl-kim commented on web/src/hooks/useToday.tsx
> +    const id = setTimeout(() => setToday(new Date()), delay)
앗 아아! 넵 수정했습니다 8e7c45eb3db75913bbe5b819658d76e2c0d877e6 
추가로 진행하다보니 하루 시작시간이 0시가 아니어서 수정했습니다 688d200ae01c029195d844603200e0dda3ffd7ac

2023-11-07 13:49 UTC, f-lab-jake commented on web/src/hooks/useToday.tsx
> +    const id = setTimeout(() => setToday(new Date()), delay)
왜 `setToday(tomorrow)`를 해야하는지 내일까지 설명을 준비해옵시다.

2023-11-10 06:09 UTC, merged

2023-11-10 09:06 UTC, f-lab-jake commented on web/src/App.tsx
> +            graphQLClientConfig={{
이코드를 분리를 하면 좋겠네요.
사실 분리하는게 자명하고 쉬운 일이지만, 반대로 코테 과제로 낼때 이런 자명한게 눈에 밟혀서 점수가 깎일수있습니다.